# Generated by Django 4.0.3 on 2022-10-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_staff_s_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='userslist',
            name='starttime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
