# Generated by Django 4.0.3 on 2022-10-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_userslist_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='s_status',
            field=models.BooleanField(default=False),
        ),
    ]
