# Generated by Django 4.0.3 on 2022-10-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_staff_s_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userslist',
            name='starttime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
