# Generated by Django 4.0.3 on 2022-10-17 05:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_staff_s_endtime_alter_staff_s_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='userslist',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userslist',
            name='uname',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userslist',
            name='lname',
            field=models.CharField(max_length=50),
        ),
    ]
