# Generated by Django 4.0.3 on 2022-10-18 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_userslist_password_userslist_uname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userslist',
            name='profile_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
