# Generated by Django 4.0.3 on 2022-10-18 18:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_userslist_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='uid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.userslist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userslist',
            name='uid',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
